import Goedel4PEL.FourValued.Modal

namespace Goedel4PEL.PairedNeighborhood

universe u v

/-- Two neighborhood families separated by modal role: universal coverage and witness hit. -/
structure Frame (World : Type u) where
  universal : World → (World → Prop) → Prop
  hit : World → (World → Prop) → Prop

def BoxPlus {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos : World → Formula → Prop)
    (w : World) (φ : Formula) : Prop :=
  F.universal w (fun v => Pos v φ)

def BoxNeg {World : Type u} {Formula : Type v}
    (F : Frame World) (Neg : World → Formula → Prop)
    (w : World) (φ : Formula) : Prop :=
  F.hit w (fun v => Neg v φ)

def DiamondPlus {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos : World → Formula → Prop)
    (w : World) (φ : Formula) : Prop :=
  F.hit w (fun v => Pos v φ)

def DiamondNeg {World : Type u} {Formula : Type v}
    (F : Frame World) (Neg : World → Formula → Prop)
    (w : World) (φ : Formula) : Prop :=
  F.universal w (fun v => Neg v φ)

/-- FDE negation exchanges the positive and negative support predicates. -/
def NegationSwaps {World : Type u} {Formula : Type v}
    (Pos Neg : World → Formula → Prop) (neg : Formula → Formula) : Prop :=
  (∀ w φ, Pos w (neg φ) ↔ Neg w φ) ∧
  (∀ w φ, Neg w (neg φ) ↔ Pos w φ)

theorem diamondPlus_iff_boxNeg_neg
    {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos Neg : World → Formula → Prop)
    (neg : Formula → Formula) (hneg : NegationSwaps Pos Neg neg)
    (w : World) (φ : Formula) :
    DiamondPlus F Pos w φ ↔ BoxNeg F Neg w (neg φ) := by
  have heq : (fun v => Neg v (neg φ)) = (fun v => Pos v φ) :=
    funext (fun v => propext (hneg.2 v φ))
  rw [DiamondPlus, BoxNeg, heq]

theorem diamondNeg_iff_boxPlus_neg
    {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos Neg : World → Formula → Prop)
    (neg : Formula → Formula) (hneg : NegationSwaps Pos Neg neg)
    (w : World) (φ : Formula) :
    DiamondNeg F Neg w φ ↔ BoxPlus F Pos w (neg φ) := by
  have heq : (fun v => Pos v (neg φ)) = (fun v => Neg v φ) :=
    funext (fun v => propext (hneg.1 v φ))
  rw [DiamondNeg, BoxPlus, heq]

theorem boxPlus_iff_diamondNeg_neg
    {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos Neg : World → Formula → Prop)
    (neg : Formula → Formula) (hneg : NegationSwaps Pos Neg neg)
    (w : World) (φ : Formula) :
    BoxPlus F Pos w φ ↔ DiamondNeg F Neg w (neg φ) := by
  have heq : (fun v => Neg v (neg φ)) = (fun v => Pos v φ) :=
    funext (fun v => propext (hneg.2 v φ))
  rw [BoxPlus, DiamondNeg, heq]

theorem boxNeg_iff_diamondPlus_neg
    {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos Neg : World → Formula → Prop)
    (neg : Formula → Formula) (hneg : NegationSwaps Pos Neg neg)
    (w : World) (φ : Formula) :
    BoxNeg F Neg w φ ↔ DiamondPlus F Pos w (neg φ) := by
  have heq : (fun v => Pos v (neg φ)) = (fun v => Neg v φ) :=
    funext (fun v => propext (hneg.1 v φ))
  rw [BoxNeg, DiamondPlus, heq]

/-- The canonical paired-neighborhood frame generated by a Kripke relation. -/
def ofRelation {World : Type u} (R : World → World → Prop) : Frame World where
  universal := fun w X => ∀ v, R w v → X v
  hit := fun w X => ∃ v, R w v ∧ X v

@[simp] theorem boxPlus_ofRelation_iff
    {World : Type u} {Formula : Type v}
    (R : World → World → Prop) (Pos : World → Formula → Prop)
    (w : World) (φ : Formula) :
    BoxPlus (ofRelation R) Pos w φ ↔ Goedel4PEL.Modal.BoxPlus R Pos w φ :=
  Iff.rfl

@[simp] theorem boxNeg_ofRelation_iff
    {World : Type u} {Formula : Type v}
    (R : World → World → Prop) (Neg : World → Formula → Prop)
    (w : World) (φ : Formula) :
    BoxNeg (ofRelation R) Neg w φ ↔ Goedel4PEL.Modal.BoxNeg R Neg w φ :=
  Iff.rfl

@[simp] theorem diamondPlus_ofRelation_iff
    {World : Type u} {Formula : Type v}
    (R : World → World → Prop) (Pos : World → Formula → Prop)
    (w : World) (φ : Formula) :
    DiamondPlus (ofRelation R) Pos w φ ↔ Goedel4PEL.Modal.DiamondPlus R Pos w φ :=
  Iff.rfl

@[simp] theorem diamondNeg_ofRelation_iff
    {World : Type u} {Formula : Type v}
    (R : World → World → Prop) (Neg : World → Formula → Prop)
    (w : World) (φ : Formula) :
    DiamondNeg (ofRelation R) Neg w φ ↔ Goedel4PEL.Modal.DiamondNeg R Neg w φ :=
  Iff.rfl

/-- Complement duality is the exact local condition used for classical modal recovery. -/
def ComplementDual {World : Type u} (F : Frame World) : Prop :=
  ∀ w X, F.universal w X ↔ ¬ F.hit w (fun v => ¬ X v)

theorem ofRelation_complementDual
    {World : Type u} (R : World → World → Prop) :
    ComplementDual (ofRelation R) := by
  intro w X
  constructor
  · intro hUniversal hHit
    rcases hHit with ⟨v, hwv, hv⟩
    exact hv (hUniversal v hwv)
  · intro hNoHit v hwv
    exact Classical.byContradiction (fun hv => hNoHit ⟨v, hwv, hv⟩)

/-- A bilateral valuation is classical when negative support is pointwise the complement of positive support. -/
def ClassicalSupport {World : Type u} {Formula : Type v}
    (Pos Neg : World → Formula → Prop) : Prop :=
  ∀ w φ, Neg w φ ↔ ¬ Pos w φ

theorem boxNeg_iff_not_boxPlus_of_complementDual
    {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos Neg : World → Formula → Prop)
    (hCD : ComplementDual F) (hClassical : ClassicalSupport Pos Neg)
    (w : World) (φ : Formula) :
    BoxNeg F Neg w φ ↔ ¬ BoxPlus F Pos w φ := by
  classical
  have heq : (fun v => Neg v φ) = (fun v => ¬ Pos v φ) :=
    funext (fun v => propext (hClassical v φ))
  rw [BoxNeg, BoxPlus, heq]
  have hDual := hCD w (fun v => Pos v φ)
  constructor
  · intro hHit hUniversal
    exact (hDual.mp hUniversal) hHit
  · intro hNotUniversal
    exact Classical.byContradiction
      (fun hNotHit => hNotUniversal (hDual.mpr hNotHit))

theorem diamondNeg_iff_not_diamondPlus_of_complementDual
    {World : Type u} {Formula : Type v}
    (F : Frame World) (Pos Neg : World → Formula → Prop)
    (hCD : ComplementDual F) (hClassical : ClassicalSupport Pos Neg)
    (w : World) (φ : Formula) :
    DiamondNeg F Neg w φ ↔ ¬ DiamondPlus F Pos w φ := by
  classical
  have heq : (fun v => Neg v φ) = (fun v => ¬ Pos v φ) :=
    funext (fun v => propext (hClassical v φ))
  rw [DiamondNeg, DiamondPlus, heq]
  have hDouble : (fun v => ¬ ¬ Pos v φ) = (fun v => Pos v φ) :=
    funext (fun v => propext ⟨
      fun h => Classical.byContradiction (fun hn => h hn),
      fun h hn => hn h⟩)
  have hDual := hCD w (fun v => ¬ Pos v φ)
  rw [hDouble] at hDual
  exact hDual

end Goedel4PEL.PairedNeighborhood
