from itertools import product

from checker import Val


ENTITIES = ("a", "b")

BOT = (Val.F, Val.F)
A = (Val.T, Val.F)
NOT_A = (Val.F, Val.T)
GENERATOR = (Val.T, Val.N)
TOP = (Val.T, Val.T)

# A genuinely four-valued subalgebra: the Godlike coordinate a excludes B so
# that relevant exemplification consistency can hold, while b ranges over all
# four values. Gaps and gluts therefore both remain present in the domain.
ADMISSIBLE = tuple(product((Val.T, Val.F, Val.N), (Val.T, Val.F, Val.N, Val.B)))


def idx(x):
    return ENTITIES.index(x)


def pos(extension, x):
    return extension[idx(x)].pos


def neg(extension, x):
    return extension[idx(x)].neg


def val(pos_support, neg_support):
    return Val((int(bool(pos_support)), int(bool(neg_support))))


def fde_neg(extension):
    return tuple(v.negate() for v in extension)


def fde_conj(x, y):
    return tuple(
        val(vx.pos and vy.pos, vx.neg or vy.neg)
        for vx, vy in zip(x, y)
    )


def fde_disj(x, y):
    return tuple(
        val(vx.pos or vy.pos, vx.neg and vy.neg)
        for vx, vy in zip(x, y)
    )


def truth_le(x, y):
    return all(
        (not vx.pos or vy.pos) and (not vy.neg or vx.neg)
        for vx, vy in zip(x, y)
    )


def p_pos(extension):
    # The principal truth-order filter generated by (T, N). It consists of
    # GENERATOR and TOP, and distinguishes a from b at the profile level.
    return truth_le(GENERATOR, extension)


def p_neg(extension):
    # Bilateral polarity: -P(X) iff +P(not X).
    return p_pos(fde_neg(extension))


def god_plus(x):
    return all(
        not p_pos(extension) or pos(extension, x)
        for extension in ADMISSIBLE
    )


def comp_pg():
    return all(
        p_pos(extension) or p_neg(extension)
        for x in ENTITIES
        if god_plus(x)
        for extension in ADMISSIBLE
        if pos(extension, x)
    )


def cons_gg():
    return all(
        not neg(extension, x)
        for x in ENTITIES
        if god_plus(x)
        for extension in ADMISSIBLE
        if pos(extension, x)
    )


def algebra_closed():
    return (
        all(fde_neg(x) in ADMISSIBLE for x in ADMISSIBLE)
        and all(fde_conj(x, y) in ADMISSIBLE for x in ADMISSIBLE for y in ADMISSIBLE)
        and all(fde_disj(x, y) in ADMISSIBLE for x in ADMISSIBLE for y in ADMISSIBLE)
    )


def delta_filter():
    return (
        p_pos(TOP)
        and not p_pos(BOT)
        and all(
            not (p_pos(x) and truth_le(x, y)) or p_pos(y)
            for x in ADMISSIBLE
            for y in ADMISSIBLE
        )
        and all(
            not (p_pos(x) and p_pos(y)) or p_pos(fde_conj(x, y))
            for x in ADMISSIBLE
            for y in ADMISSIBLE
        )
    )


def complement_decision():
    return all(p_pos(x) or p_pos(fde_neg(x)) for x in ADMISSIBLE)


def positive_profile_eq(x, y):
    return all(
        pos(extension, x) == pos(extension, y)
        for extension in ADMISSIBLE
        if p_pos(extension)
    )


def profile_saturated():
    return all(
        pos(extension, x) == pos(extension, y)
        and neg(extension, x) == neg(extension, y)
        for x in ENTITIES
        for y in ENTITIES
        if positive_profile_eq(x, y)
        for extension in ADMISSIBLE
    )


def validate_delta_filter_does_not_restore_comp():
    assert algebra_closed()
    assert any(Val.N in extension for extension in ADMISSIBLE)
    assert any(Val.B in extension for extension in ADMISSIBLE)
    assert delta_filter()
    assert profile_saturated()
    assert god_plus("a")
    assert not god_plus("b")
    assert cons_gg()

    # The proper filter is not maximal: A and its complement are both gaps.
    assert not p_pos(A)
    assert not p_pos(fde_neg(A))
    assert not complement_decision()

    # A is possessed by a Godlike witness but neither positively nor negatively
    # classified by P, so COMP remains false despite the filter and consistency.
    assert pos(A, "a")
    assert not p_neg(A)
    assert not comp_pg()
    return True


if __name__ == "__main__":
    assert validate_delta_filter_does_not_restore_comp()
    print("Gate 8 profile delta-filter without ultrafilter maximality or COMP: OK")
